{{- if eq .Values.global.passportLocation "on-cluster" }}
apiVersion: v1
kind: Secret
metadata:
  name: passport-creds
  labels:
    heritage: drycc
data:
  {{- if (.Values.databaseUrl) }}
  database-url: {{ .Values.databaseUrl | b64enc }}
  {{- end }}
  {{- if (.Values.databaseReplicaUrl) }}
  database-replica-url: {{ .Values.databaseReplicaUrl | b64enc }}
  {{- end }}
  django-secret-key: {{ (include "common.secrets.lookup" (dict "secret" "passport-creds" "key" "django-secret-key" "defaultValue" (randAscii 64) "context" $)) }}
  oidc-rsa-private-key: {{genPrivateKey "rsa" | b64enc}}
  {{- range $item := .Values.initApplications }}
  {{- if ($item.prefix) }}
  {{- $name := ($item.name | replace " " "-" | lower) }}
  drycc-passport-{{$name}}-key: {{ (include "common.secrets.lookup" (dict "secret" "passport-creds" "key" "drycc-passport-($name)-key" "defaultValue" ($item.key | default (randAlphaNum 40)) "context" $)) }}
  drycc-passport-{{$name}}-secret: {{ (include "common.secrets.lookup" (dict "secret" "passport-creds" "key" "drycc-passport-($name)-secret" "defaultValue" ($item.secret | default (randAlphaNum 64)) "context" $)) }}
  {{- end }}
  {{- end }}
{{- end }}
