{{- if eq .Values.global.passportLocation "on-cluster" }}
apiVersion: v1
kind: Secret
metadata:
  name: passport-creds
  labels:
    heritage: drycc
  annotations:
    "helm.sh/hook": pre-install
data:
  {{- if (.Values.databaseUrl) }}
  database-url: {{ .Values.databaseUrl | b64enc }}
  {{- end }}
  {{- if (.Values.databaseReplicaUrl) }}
  database-replica-url: {{ .Values.databaseReplicaUrl | b64enc }}
  {{- end }}
  django-secret-key: {{ randAscii 64 | b64enc }}
  oidc-rsa-private-key: "{{genPrivateKey "rsa" | b64enc}}"
  {{- range $item := .Values.initApplications }}
  {{- if ($item.prefix) }}
  drycc-passport-{{$item.name | replace " " "-" | lower}}-key: {{ if $item.key | default "" | ne "" }}{{ $item.key | b64enc }}{{ else }}{{ randAlphaNum 40 | b64enc }}{{ end }}
  drycc-passport-{{$item.name | replace " " "-" | lower}}-secret: {{ if $item.secret | default "" | ne "" }}{{ $item.secret | b64enc }}{{ else }}{{ randAlphaNum 64 | b64enc }}{{ end }}
  {{- end }}
  {{- end }}
{{- end }}
