{{- if eq .Values.global.passport_location "on-cluster" }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "passport-api-server"
  labels:
    app: "passport"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/tls-acme: "true"
    {{- if not (eq .Values.global.ingress_class "") }}
    kubernetes.io/ingress.class: "{{ .Values.global.ingress_class }}"
    {{ end }}
spec:
  rules:
  - host: drycc-passport.{{ .Values.global.platform_domain }}
    http:
      paths:
      {{- if eq .Values.global.ingress_class "gce" "alb" }}
      - path: /*
      {{- else }}{{/* Has annotations but ingress class is not "gce" nor "alb" */}}
      - path: /
      {{- end }}
        backend:
          serviceName: drycc-passport
          servicePort: 80
  {{ if .Values.global.cert_passport_enabled }}
  tls:
    - secretName: drycc-passport-certificate-auto
      hosts:
        - drycc.{{ .Values.global.platform_domain }}
  {{- end }}
{{- end }}
