apiVersion: v1
kind: ConfigMap
metadata:
  name: passport-config
  labels:
    heritage: drycc
data:
  reserved-usernames.txt: |-
{{- if .Values.reservedUsernames }}
{{- (tpl .Values.reservedUsernames $) | nindent 4 }}
{{- else}}
{{- include "passport.defaultReservedUsernames" . | nindent 4 }}
{{- end }}
  init-applications.json: |-
{{ toPrettyJson .Values.initApplications | indent 4 }}
