{{- if eq .Values.global.passportLocation "on-cluster" }}
apiVersion: v1
kind: Secret
metadata:
  name: passport-creds
  labels:
    heritage: drycc
  annotations:
    "helm.sh/hook": pre-install
data:
  {{- if (.Values.databaseUrl) }}
  database-url: {{ .Values.databaseUrl | b64enc }}
  {{- end }}
  django-secret-key: {{ randAscii 64 | b64enc }}
  drycc-passport-controller-key: {{ randAlphaNum 40 | b64enc }}
  drycc-passport-controller-secret: {{ randAlphaNum 64 | b64enc }}
  {{- if eq .Values.global.grafanaLocation "on-cluster" }}
  drycc-passport-grafana-key: {{ randAlphaNum 40 | b64enc }}
  drycc-passport-grafana-secret: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
  oidc-rsa-private-key: "{{genPrivateKey "rsa" | b64enc}}"
{{- end }}
