{{- if eq .Values.global.passport_location "on-cluster" }}
apiVersion: v1
kind: Secret
metadata:
  name: passport-creds
  labels:
    heritage: drycc
  annotations:
    "helm.sh/hook": pre-install
data:
  {{- if (.Values.database_url) }}
  database-url: {{ .Values.database_url | b64enc }}
  {{- end }}
  django-secret-key: {{ randAscii 64 | b64enc }}
  social-auth-drycc-controller-key: {{ randAscii 40 | b64enc }}
  social-auth-drycc-controller-secret: {{ randAscii 64 | b64enc }}
  oidc-rsa-private-key: "{{genPrivateKey "rsa" | b64enc}}"
{{- end }}
