{{- if eq .Values.global.passportLocation "on-cluster" }}
{{- if .Values.global.certManagerEnabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drycc-passport
spec:
  secretName: drycc-passport-auto-tls
  issuerRef:
    name: drycc-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - drycc-passport.{{ .Values.global.platformDomain }}
  privateKey:
    rotationPolicy: Always
{{- end }}
{{- end }}
