{{- if eq .Values.global.passportLocation "on-cluster" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: passport-config
  labels:
    heritage: drycc
data:
data:
  init-applications.json: |-
{{ toPrettyJson .Values.initApplications | indent 4 }}
{{- end }}
