# Generated by Django 5.2.13 on 2026-04-23 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_application_allowed_origins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='authorization_grant_type',
            field=models.CharField(choices=[('authorization-code', 'Authorization code'), ('urn:ietf:params:oauth:grant-type:device_code', 'Device Code'), ('implicit', 'Implicit'), ('password', 'Resource owner password-based'), ('client-credentials', 'Client credentials'), ('openid-hybrid', 'OpenID connect hybrid')], max_length=44),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('system', 'System'), ('product', 'Product Updates'), ('security', 'Security'), ('alert', 'Alerts'), ('service', 'Service')], default='system', max_length=20, verbose_name='category')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('full_content', models.TextField(blank=True, verbose_name='full content')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=20, verbose_name='severity')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('action_link', models.CharField(blank=True, max_length=500, verbose_name='action link')),
                ('action_text', models.CharField(blank=True, max_length=255, verbose_name='action text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alerts', models.BooleanField(default=True, verbose_name='email alerts')),
                ('push_alerts', models.BooleanField(default=False, verbose_name='push alerts')),
                ('webhook_url', models.URLField(blank=True, max_length=500, verbose_name='webhook url')),
                ('notify_security', models.BooleanField(default=True, verbose_name='notify security')),
                ('notify_system', models.BooleanField(default=True, verbose_name='notify system')),
                ('notify_product', models.BooleanField(default=False, verbose_name='notify product')),
                ('notify_alert', models.BooleanField(default=True, verbose_name='notify alert')),
                ('notify_service', models.BooleanField(default=True, verbose_name='notify service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_preference', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'message preference',
                'verbose_name_plural': 'message preferences',
            },
        ),
    ]
