# Generated by Django 5.2.8 on 2026-01-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_organization_organizationinvitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='alerts',
            field=models.BooleanField(default=True),
        ),
    ]
