# Generated by Django 5.2.13 on 2026-05-09 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def forward_data_migration(apps, schema_editor):
    Application = apps.get_model('api', 'Application')
    oauth2_settings = getattr(settings, 'OAUTH2_PROVIDER', {})
    default_provider_scopes_list = oauth2_settings.get("DEFAULT_SCOPES", ['openid', 'email', 'profile'])
    default_provider_scopes = " ".join(default_provider_scopes_list)

    for app in Application.objects.all():
        if not app.allowed_scopes:
            app.allowed_scopes = default_provider_scopes
        
        if app.name.lower() in ("controller", "grafana"):
            app.authorization_grant_type = "internal"
            
        app.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_application_authorization_grant_type_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='allowed_scopes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(forward_data_migration, reverse_code=migrations.RunPython.noop),
    ]