imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"

nodeAffinityPreset:
  key: "drycc.cc/node"
  type: "soft"
  values:
  - "true"

podAffinityPreset:
  key: "security"
  type: ""
  values:
  - "drycc-security"

podAntiAffinityPreset:
  key: "app"
  type: "soft"
  values:
  - "drycc-passport"

# Set passport deployment replicas
replicas: 1
# limitsCpu: "100m"
# limitsMemory: "50Mi"
## databaseUrl and databaseReplicaUrl are will no longer use the built-in database component
databaseUrl: ""
databaseReplicaUrl: ""
# Any custom controller environment variables
# can be specified as key-value pairs under environment
# this is usually a non required setting.
environment:
## General settings
#  DRYCC_DEBUG: False
#  ADMIN_ENABLED: False
#  REGISTRATION_ENABLED: False
## LDAP setting
#  LDAP_ENDPOINT: ""
#  LDAP_BIND_DN: ""
#  LDAP_BIND_PASSWORD: ""
#  LDAP_USER_BASEDN: ""
#  LDAP_USER_FILTER: ""
#  LDAP_GROUP_BASEDN: ""
#  LDAP_GROUP_FILTER: ""
#  LDAP_ACTIVE_GROUP: ""
#  LDAP_STAFF_GROUP: ""
#  LDAP_SUPERUSER_GROUP:  ""
## OATUH2 setting
#  ACCESS_TOKEN_EXPIRE_SECONDS: 2592000
#  ID_TOKEN_EXPIRE_SECONDS: 2592000
#  AUTHORIZATION_CODE_EXPIRE_SECONDS: 600
#  CLIENT_SECRET_GENERATOR_LENGTH: 64
#  REFRESH_TOKEN_EXPIRE_SECONDS: 5184000
## EAMIL setting
#  EMAIL_HOST: ""
#  EMAIL_PORT: ""
#  DEFAULT_FROM_EMAIL: ""
#  EMAIL_HOST_USER: ""
#  EMAIL_HOST_PASSWORD: ""
#  EMAIL_USE_TLS: ""
#  EMAIL_USE_SSL: ""
# Used to create Django admin users
adminUsername: "admin"
adminPassword: "admin"
adminEmail: "admin@email.com"

# Service
service:
  # Provide any additional service annotations
  annotations: {}

redis:
  replicas: 1

global:
  # Set the location of Workflow's grafana instance
  #
  # Valid values are:
  # - on-cluster: Run Grafana within the Kubernetes cluster
  # - off-cluster: Grafana is running outside of the cluster
  grafanaLocation: "on-cluster"

  # Admin email, used for each component to send email to administrator
  email: "drycc@drycc.cc"
  # Set the location of Workflow's PostgreSQL database
  #
  # Valid values are:
  # - on-cluster: Run PostgreSQL within the Kubernetes cluster (credentials are generated
  #   automatically; backups are sent to object storage
  #   configured above)
  # - off-cluster: Run PostgreSQL outside the Kubernetes cluster (configure in database section)
  databaseLocation: "on-cluster"

  # Please check `kubernetes.io/ingress.class`
  ingressClass: ""
  # A domain name consists of one or more parts.
  # Periods (.) are used to separate these parts.
  # Each part must be 1 to 63 characters in length and can contain lowercase letters, digits, and hyphens (-).
  # It must start and end with a lowercase letter or digit.
  clusterDomain: "cluster.local"
  # The public resolvable hostname to build your cluster with.
  #
  # This will be the hostname that is used to build endpoints such as "drycc.$HOSTNAME"
  platformDomain: ""
  # Whether cert_passport is enabled to automatically generate passport certificates
  certManagerEnabled: true
  passportLocation: "on-cluster"
